ktor:
  deployment:
    port: 8080
  application:
    modules:
      - dev.pkolosinski.gytt.server.AppRunnerKt.rootModule

couchbase:
  url: ${COUCHBASE_URL:couchbase://localhost}
  username: ${COUCHBASE_USERNAME:app_user}
  password: ${COUCHBASE_PASSWORD:password}
  bucket: ${COUCHBASE_BUCKET:gytt}
